### ISSUE TITLE
모바일프로그래밍 화목12 팀원 지원합니다

### ISSUE THREAD

**Issue by hwangsujeong99** [CloseHeart/mobile-recruiting#1]
# 모바일 프로그래밍 팀원 지원

## 기본 사항
* 이름 : 황수정
* 학과 : 소프트웨어학과
* 학년 : 3학년

## 기타 자료

Github주소: https://github.com/hwangsujeong99/chatting_client
알고리즘(3명)과 컴퓨터네트워크(혼자) 프로젝트 진행하여 모두 전반적인 디자인 부분에 큰 역할을 하였습니다. 사진은 초기 gui디자인 시안입니다.(좀 급하게 만들었던 것도 있어서 아직 폰트나 기타 기능이 적용되지 않은 부분도 있습니다.)

![1614819909197](https://user-images.githubusercontent.com/74967616/109894712-5326e880-7cd1-11eb-8276-7e54bd6f6525.png)
![1614819908008](https://user-images.githubusercontent.com/74967616/109894738-5e7a1400-7cd1-11eb-947a-38a9318dda47.png)
![1614819906982](https://user-images.githubusercontent.com/74967616/109894752-63d75e80-7cd1-11eb-8737-abba8dbdcc71.png)
![1614819906101](https://user-images.githubusercontent.com/74967616/109894759-68037c00-7cd1-11eb-9bb8-dcebd128c81d.png)

자바 기술은 많이 부족하지만 제가 할 수 있는 부분들은 최대한 찾아 배우고 열심히 임하겠습니다.

**Comment by Aftermoon-dev** [comment]
안녕하세요! 지원해주셔서 감사합니다!

모든 진행 상황은 해당 Issue 글을 통해 알려드릴 예정이니, 오른쪽 Notifications이 만약 Subscribe로 표시된다면 꼭 Subscribe를 해주세요! (이메일로 해당 글에 새로운 답글이 달리면 알람이 갈 것입니다!)

감사합니다 :)

**Comment by Aftermoon-dev** [comment]
안녕하세요! 아쉽게도 논의 결과 다른 분과 함께하게 되었습니다.
같은 팀으로 진행하지는 못하게 되었으나, 다른 팀에서도 좋은 결과 있으시기를 바라겠습니다!
