### ISSUE TITLE
모바일 프로젝트 팀원 지원

### ISSUE THREAD

**Issue by subinga18** [CloseHeart/mobile-recruiting#2]
# 모바일 프로그래밍 팀원 지원합니다

## 기본 사항
* 이름 : 김수빈
* 학과 : 소프트웨어학과
* 학년 : 3 

## 기타 자료
2019년도 알고리즘 텀프로젝트 ( 3인 1팀 )
GUI 부분을 담당해서 진행하였습니다. 
<img width="707" alt="스크린샷 2021-03-04 오전 10 27 45" src="https://user-images.githubusercontent.com/38221941/109896847-05ac7a80-7cd5-11eb-9351-1787adae9970.png">
<img width="691" alt="스크린샷 2021-03-04 오전 10 27 30" src="https://user-images.githubusercontent.com/38221941/109896867-0d6c1f00-7cd5-11eb-84cf-71f250c1bfda.png">
<img width="471" alt="스크린샷 2021-03-04 오전 10 28 39" src="https://user-images.githubusercontent.com/38221941/109896875-13620000-7cd5-11eb-9878-1ac75b666a0f.png">

2019년도 네트워크 텀프로젝트 ( 5인 1팀 )
GUI 부분을 담당하여 진행하였습니다. 
<img width="333" alt="스크린샷 2021-03-04 오전 10 31 38" src="https://user-images.githubusercontent.com/38221941/109897023-6b006b80-7cd5-11eb-9275-5fb26d4ca35d.png">

두 프로젝트 모두 게임 프로젝트라 
이미지를 찾고 배치하고 편집해서 실제 게임 같은 화면을 만들어내는것에 집중하였습니다.
휴학 후 복학한 터라 코딩 실력이 좀 떨어졌을 수도 있지만 최대한 찾아보고 공부하겠습니다. 
안드로이드 스튜디오는 써보긴 했는데 맛보기 정도만 해봤습니다.

**Comment by Aftermoon-dev** [comment]
안녕하세요! 지원해주셔서 감사합니다!

모든 진행 상황은 해당 Issue 글을 통해 알려드릴 예정이니, 오른쪽 Notifications이 만약 Subscribe로 표시된다면 꼭 Subscribe를 해주세요! (이메일로 해당 글에 새로운 답글이 달리면 알람이 갈 것입니다!)

감사합니다 :)

**Comment by Aftermoon-dev** [comment]
안녕하세요 :) 

팀원들과 논의 끝에 김수빈님으로 최종 결정되었습니다!

시간 되실때 카카오톡 ID ddol0225 친구추가 해주셔서 연락주시면 감사하겠습니다!

앞으로 잘 부탁 드립니다 :)
