### ISSUE TITLE
모바일 프로그래밍 팀원 지원

### ISSUE THREAD

**Issue by General-code** [CloseHeart/mobile-recruiting#3]
# 모바일 프로그래밍 팀원 지원

## 기본 사항
* 이름 : 배용호
* 학과 : 소프트웨어학과
* 학년 : 3
* 주력언어 : 없음(C++을 가장 많이 사용 했지만 중급자의 경지에 다다르지 못했다고 생각합니다. STL과 move semantics 를 공부했습니다.) Java는 객체지향에서 배웠습니다(2019년도에 A+받았습니다. 성적이 실력을 말하지는 않지만 성실함을 보여주고자 썼습니다). 자바가 주력 언어가 아니여서 오랜만에 다시 공부했습니다. 
skill set: c++ ***
java *
c *
python *
javascript *
mongoDB *

## 기타 자료

![1](https://user-images.githubusercontent.com/11516889/109900312-81f58c80-7cda-11eb-8917-faa08c62a6cb.PNG)
![2](https://user-images.githubusercontent.com/11516889/109900320-8457e680-7cda-11eb-88e9-fd80026da4d8.PNG)
![3](https://user-images.githubusercontent.com/11516889/109900324-8621aa00-7cda-11eb-94e2-02f740f1c4b6.PNG)
![4](https://user-images.githubusercontent.com/11516889/109900330-8752d700-7cda-11eb-951b-a7395b9e2039.PNG)

부트스트랩으로 디자인을 했습니다. 자바스크립트로 패턴 검사를 했고 sweet alert 같은 라이브러리를 써서 fail과 success를 기본 프롬프트와 다르게 했습니다. 

![5](https://user-images.githubusercontent.com/11516889/109900509-d6990780-7cda-11eb-8245-0e07a32f41b2.PNG)
만들기는 했는데 데이터베이스 중복문제가 있어서 mongoDB를 다룰 때 파이썬에서 필터링을 했습니다. 

이 팀에서 꼭 개발하고 싶어요. 앱 디자인도 열심히 하겠지만 앱이 돌아가는 코드 구조 전반을 이해하고 응용할 수 있는 능력을 기르고 싶습니다. 여기에는 다양한 분들이 많이 계신 것 같고 안드로이드 위주 개발을 경험한 분이 있기 때문에 더욱더 하고 싶습니다.  깃헙의 사용법은 서투르지만 빠르게 배우는 것은 자신이 있습니다. 데이터과학을 배우기 위해 필요한 파이썬을 3일만에 공부했습니다.(사실 느린 것일 수도 있지만) 미리 계획된 일에 대해서 빠르게 공부하는 데에는 자신이 있습니다.

**Comment by Aftermoon-dev** [comment]
안녕하세요! 지원해주셔서 감사합니다!

모든 진행 상황은 해당 Issue 글을 통해 알려드릴 예정이니, 오른쪽 Notifications이 만약 Subscribe로 표시된다면 꼭 Subscribe를 해주세요! (이메일로 해당 글에 새로운 답글이 달리면 알람이 갈 것입니다!)

감사합니다 :)

**Comment by Aftermoon-dev** [comment]
안녕하세요! 아쉽게도 논의 결과 다른 분과 함께하게 되었습니다.
같은 팀으로 진행하지는 못하게 되었으나, 다른 팀에서도 좋은 결과 있으시기를 바라겠습니다!

**Comment by General-code** [comment]
먼저 죄송하지만
제가 궁금한게 하나 있는데요 혹시 지원자분 중 선택되지 않은 다른 한 분에 대해서 알려주실 수 있을까요?
팀원을 구하는데 아무래도 지원한 사람이 열정적인 것 같아서요.
-----Original Message-----
